import { FaPlus } from "react-icons/fa";

export const Data = [
    {
        name: "SM Marketing",
        price:" $250 USD/Monthly",
        icon: <FaPlus  size={20}/>,
        item1: "Facebook",
        item2: "Instagram",
        item3: "Youtube  (On Request)",
        item4: "TikTok  (On Request)",
        item5: "Twitter  (On Request)",
        id: 12,
    },
    {
        name: "Basic Website",
        price: "$450 USD",
        app1: "customized $ 5,000",
        app2: "Landing page  $ 1,000",
        app3: "E-commerce  $ 10,000",
        icon: <FaPlus  size={20}/>,
        item1: "Than 4 - 5 Pages",
        item2: "Standard Design",
        item3: "Professional Content",
        item4: "",
        item5: "",
        id: 1,
    },
    {
        name: "E Commerce (Basic)",
        price: "$700 - 1000 USD",
        icon: <FaPlus  size={20}/>,
        item1: "Than 4 - 5 Pages",
        item2: "Standard Design",
        item3: "Professional Content",
        item4: "Customized E Commerce System",
        item5: "Basic Admin Dashboard",
        id: 2,
    },
    {
        name: "E Commerce (Advance)",
        price:"$1500 - 1800 USD",
        icon: <FaPlus  size={20}/>,
        item1: "More Than 4 - 5 Pages",
        item2: "Standard Design",
        item3: "Professional Content",
        item4: "Customized E Commerce System",
        item5: "Advanced Admin Dashboard",
        id:3,
    },
    {
        name: "Affiliate Website",
        price: "$600 USD",
        icon: <FaPlus  size={20}/>,
        item1: "More Than 4 - 5 Pages",
        item2: "Standard Design",
        item3: "Professional Content",
        item4: "",
        item5: "",
        id: 4,
    },
    {
        name: "Graphic Design",
        price: "$100 USD",
        icon: <FaPlus  size={20}/>,
        item1: "5 Static Banners",
        item2: "",
        item3: "",
        item4: "",
        item5: "",
        id:5,
    },
    {
        name: "Video Editing",
        price:" $100 USD",
        icon: <FaPlus  size={20}/>,
        item1: "1 - 1.5 Mins",
        item2: "",
        item3: "",
        item4: "",
        item5: "",
        id: 6,
    },
    {
        name: "Lead Generation",
        price: "$100 USD",
        icon: <FaPlus  size={20}/>,
        item1: "50 legit lead",
        item2: "",
        item3: "",
        item4: "",
        item5: "",
        id: 7,
    },
    {
        name: "Mobile App",
        price: "$1000 - 10,000 USD",
        app1: "full app $ 5,000",
        app2: "Mini app $ 1,000",
        app3: "IOS/Android app $ 10,000",
        icon: <FaPlus  size={20}/>,
        item1: "Pending On Requirements",
        item2: "",
        item3: "",
        item4: "",
        item5: "",
        id: 8,
    },
    {
        name: "Logo Packages/Logo Redo",
        price:"$100 USD",
        icon: <FaPlus  size={20}/>,
        item1: "1 Logo",
        item2: "3 Revisions",
        item3: "3 Business Cards",
        item4: "",
        item5: "",
        id: 9,
    },
    {
        name: "SEO",
        price: "$200 USD/Monthly",
        icon: <FaPlus  size={20}/>,
        item1: " Advanced Targeted SEO",
        item2: "",
        item3: "",
        item4: "",
        item5: "",
        id: 10,
    },
    {
        name: "Pixel/Analytic Code Integration",
        price: "$100 USD",
        icon: <FaPlus  size={20}/>,
        item1: "Standard Analytic Dashboard",
        item2: "Deep Analytic Insight",
        item3: "",
        item4: "",
        item5: "",
        id: 11,
        
    },
    
]